### PR TITLE
Fix build for base >= 4.13, update lts resolver

### LINKED ISSUE #89: Doesn't compile with haskell compiler 8.8.3
I have just installed the latest haskell platform, running `stack ghc -- --version` shows `8.8.3`, and I get the following error when running `jake`:
```
src/Common/Error.hs:138:3: error:
    ‘fail’ is not a (visible) method of class ‘Monad’
    |
138 |   fail s        = Error (ErrorGeneral rangeNull (text s)) []
    |   ^^^^
> ghc -c src/Common/Error.hs -fwarn-incomplete-patterns -iout/debug -odir out/debug -hidir out/debug 
```

Quick googling showed this [gitlab issue](https://gitlab.haskell.org/ghc/ghc/issues/16849) on `ghc` with the error `8.8.1-alpha2: fail is not a (visible) method of class Monad`. 

Do I need an older version of the compiler? Thanks!

### PR DESCRIPTION
**Pull request by sternenseemann**
Resolves #89.

* Update `base` to `>= 4.13` (July 2019) and use the latest `lts` stack resolver
* Adapt code to breaking changes in `base` due to the `MonadFail` proposal. See also [base changelog](https://gitlab.haskell.org/ghc/ghc/-/blob/master/libraries/base/changelog.md#41300-july-2019)

### CODE REVIEW

**Comment by daanx** [comment]
Thanks so much!
