### ISSUE TITLE
Doesn't compile with haskell compiler 8.8.3

### ISSUE THREAD

**Issue by MargaretKrutikova** [koka-lang/koka#89]
I have just installed the latest haskell platform, running `stack ghc -- --version` shows `8.8.3`, and I get the following error when running `jake`:
```
src/Common/Error.hs:138:3: error:
    ‘fail’ is not a (visible) method of class ‘Monad’
    |
138 |   fail s        = Error (ErrorGeneral rangeNull (text s)) []
    |   ^^^^
> ghc -c src/Common/Error.hs -fwarn-incomplete-patterns -iout/debug -odir out/debug -hidir out/debug 
```

Quick googling showed this [gitlab issue](https://gitlab.haskell.org/ghc/ghc/issues/16849) on `ghc` with the error `8.8.1-alpha2: fail is not a (visible) method of class Monad`. 

Do I need an older version of the compiler? Thanks!

**Comment by sternenseemann** [comment]
These failures are related to the [implementation of the `MonadFail` proposal in base 4.13](https://gitlab.haskell.org/ghc/ghc/-/blob/master/libraries/base/changelog.md#41300-july-2019).

Easiest way to get an older base is probably using an older compiler / stack resolver, but the problem should also be trivial to fix.

**Comment by anfelor** [comment]
Hi, I think this issue is resolved? Feel free to reopen if not!
